In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os

In [4]:
data_folder = '../../data'

avel = np.array(pd.read_csv(os.path.join(data_folder, 'hhmm_avel.csv'))) * 50
fvel = np.array(pd.read_csv(os.path.join(data_folder, 'hhmm_fvel.csv')))
categories = np.array(pd.read_csv(os.path.join(data_folder, 'categories.csv')))
avel = avel[:,1:]
fvel = fvel[:,1:]
categories = categories[:,1:]
print(np.shape(avel))
print(np.shape(fvel))
print(np.shape(categories))

(498, 327)
(499, 327)
(499, 327)


In [101]:
categories.shape

(499, 327)

In [102]:
# previous_cat = categories[0, 0]
# grouped_categories = []
# intermediate_categories = []
# for element in categories[:, 0]:
#     if element == previous_cat:
#         intermediate_categories.append(int(element))
#     else:
# #         intermediate_categories.append(element)
#         grouped_categories.append(intermediate_categories)
#         intermediate_categories = [int(element)]
#     previous_cat = element
        

In [5]:
catformodel = categories[:,0]
fformodel = fvel[:,0]
aformodel = avel[:,0]

for ii in range(1,327):
    catformodel = np.concatenate((catformodel,categories[:498,ii]))
    fformodel = np.concatenate((fformodel,fvel[:498,ii]))
    aformodel = np.concatenate((aformodel,avel[:498,ii]))


print(len(catformodel))
print(len(aformodel))
print(len(fformodel))

formodel = np.reshape(catformodel, (-1,1))

162847
162846
162847


In [56]:
sampling_freq = 50
from hmmlearn import hmm
from hmmlearn.base import ConvergenceMonitor

np.random.seed(42)

highlevelmodel = hmm.GaussianHMM(n_components=6,  verbose=True, n_iter=10000)

highlevelmodel.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
print(highlevelmodel.monitor_)

ConvergenceMonitor(
    history=[],
    iter=0,
    n_iter=10000,
    tol=0.01,
    verbose=True,
)


In [55]:
categories.shape

(499, 327)

In [59]:
highlevelmodel.fit(np.concatenate(categories).reshape(-1,1), [499] * 327 )

         1     -319582.8040             +nan
         2     -241532.1808      +78050.6232
         3     -233473.8798       +8058.3010
         4     -223217.8565      +10256.0233
         5     -210226.4230      +12991.4335
         6     -164154.8697      +46071.5533
         7      179904.1911     +344059.0607
         8      183582.1791       +3677.9881
         9      184221.1561        +638.9770
        10      185148.2831        +927.1270
        11      187946.5230       +2798.2398
        12      204260.2687      +16313.7457
        13      395163.5186     +190903.2499
        14      615386.1467     +220222.6281
        15      852233.3734     +236847.2267
        16      859387.4117       +7154.0382
        17      859412.6925         +25.2809
        18      859508.8921         +96.1996
        19      860382.2605        +873.3684
        20      866377.7788       +5995.5183
        21      870242.7092       +3864.9304
        22      875235.3404       +4992.6312
        23

GaussianHMM(n_components=6, n_iter=10000, verbose=True)

In [8]:
# print(highlevelmodel.predict(categories))

# plt.figure
# plt.plot(highlevelmodel.predict(categories))

# ## check that you are inputting the data correctly here. I don't get why its all one length or not one length.

In [51]:
#set up the data for the lower level states 

a = len(aformodel)

for kk in range(1, 7):
    valsa =[]
    valsf = []
    lengths = []
    count = 0 
    for ii in range(a):
        if catformodel[ii] == kk:
            valsa.append(aformodel[ii])
            valsf.append(fformodel[ii])
            count += 1
        else:
            if count > 0:
                lengths.append(count)
            count = 0

    valsa = np.array([valsa])
    valsf = np.array([valsf])
    
    vals_af = np.concatenate([valsa, valsf])
    
#     print(valsa.shape, valsf.shape)
#     print(sum(lengths))
    if kk == 1:
        state1model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state1model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state1model.fit(vals_af.T, lengths)
        
    elif kk == 2:
        state2model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state2model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state2model.fit(vals_af.T, lengths)
    elif kk == 3:
        state3model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state3model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state3model.fit(vals_af.T, lengths)
    elif kk == 4:
        state4model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state4model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state4model.fit(vals_af.T, lengths)
    elif kk == 5:
        state5model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state5model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state5model.fit(vals_af.T, lengths)
    elif kk == 6:
        state6model = hmm.GaussianHMM(n_components=10,  verbose=True, n_iter=10000)
        state6model.monitor_ = ConvergenceMonitor(tol=0.01, n_iter=10000, verbose=True)
        state6model.fit(vals_af.T, lengths)

(1, 58563) (1, 58563)
58563
(1, 31735) (1, 31735)
31731
(1, 53341) (1, 53341)
53341
(1, 16094) (1, 16094)
16094
(1, 1570) (1, 1570)
1570
(1, 1543) (1, 1543)
1543


In [52]:
state_models = {
    1: state1model,
    2: state2model,
    3: state3model,
    4: state4model,
    5: state5model,
    6: state6model,
}

In [63]:
series = highlevelmodel.sample(499, random_state=1234)[0]
sampled_categories =  series[:, 0]

In [66]:
sampled_categories = np.round(sampled_categories)

In [67]:
sampled_categories

array([1., 3., 3., 3., 4., 3., 3., 3., 3., 3., 1., 2., 2., 2., 3., 1., 3.,
       4., 3., 3., 1., 2., 1., 5., 3., 3., 2., 1., 1., 2., 2., 3., 2., 1.,
       1., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 1., 1., 4., 2., 4., 4.,
       1., 3., 4., 4., 1., 1., 1., 1., 1., 1., 2., 1., 1., 3., 1., 4., 1.,
       3., 4., 3., 3., 4., 3., 4., 3., 2., 3., 2., 3., 3., 3., 2., 3., 2.,
       1., 1., 1., 2., 4., 4., 4., 3., 2., 1., 2., 3., 2., 2., 1., 3., 3.,
       2., 2., 1., 3., 2., 3., 4., 2., 1., 3., 2., 1., 2., 3., 3., 3., 1.,
       3., 3., 3., 2., 1., 2., 2., 1., 1., 2., 3., 4., 3., 4., 4., 3., 4.,
       3., 1., 1., 1., 3., 1., 2., 3., 3., 3., 4., 6., 1., 2., 4., 1., 4.,
       4., 2., 4., 3., 3., 4., 3., 2., 3., 3., 3., 1., 1., 3., 3., 3., 3.,
       1., 3., 4., 1., 1., 3., 2., 1., 3., 4., 2., 3., 1., 3., 4., 2., 2.,
       3., 1., 3., 3., 3., 4., 3., 1., 1., 2., 2., 2., 3., 1., 2., 1., 4.,
       2., 1., 2., 2., 1., 2., 1., 3., 1., 3., 1., 2., 1., 3., 1., 3., 3.,
       1., 3., 1., 1., 1.

In [105]:
previous_cat = sampled_categories[0]
grouped_categories = []
intermediate_categories = []
for element in sampled_categories:
    if element == previous_cat:
        intermediate_categories.append(int(element))
    else:
#         intermediate_categories.append(element)
        grouped_categories.append(intermediate_categories)
        intermediate_categories = [int(element)]
    previous_cat = element
        

In [106]:
grouped_categories

[[1],
 [3, 3, 3],
 [4],
 [3, 3, 3, 3, 3],
 [1],
 [2, 2, 2],
 [3],
 [1],
 [3],
 [4],
 [3, 3],
 [1],
 [2],
 [1],
 [5],
 [3, 3],
 [2],
 [1, 1],
 [2, 2],
 [3],
 [2],
 [1, 1],
 [2],
 [3, 3, 3, 3, 3, 3, 3, 3, 3],
 [1, 1],
 [4],
 [2],
 [4, 4],
 [1],
 [3],
 [4, 4],
 [1, 1, 1, 1, 1, 1],
 [2],
 [1, 1],
 [3],
 [1],
 [4],
 [1],
 [3],
 [4],
 [3, 3],
 [4],
 [3],
 [4],
 [3],
 [2],
 [3],
 [2],
 [3, 3, 3],
 [2],
 [3],
 [2],
 [1, 1, 1],
 [2],
 [4, 4, 4],
 [3],
 [2],
 [1],
 [2],
 [3],
 [2, 2],
 [1],
 [3, 3],
 [2, 2],
 [1],
 [3],
 [2],
 [3],
 [4],
 [2],
 [1],
 [3],
 [2],
 [1],
 [2],
 [3, 3, 3],
 [1],
 [3, 3, 3],
 [2],
 [1],
 [2, 2],
 [1, 1],
 [2],
 [3],
 [4],
 [3],
 [4, 4],
 [3],
 [4],
 [3],
 [1, 1, 1],
 [3],
 [1],
 [2],
 [3, 3, 3],
 [4],
 [6],
 [1],
 [2],
 [4],
 [1],
 [4, 4],
 [2],
 [4],
 [3, 3],
 [4],
 [3],
 [2],
 [3, 3, 3],
 [1, 1],
 [3, 3, 3, 3],
 [1],
 [3],
 [4],
 [1, 1],
 [3],
 [2],
 [1],
 [3],
 [4],
 [2],
 [3],
 [1],
 [3],
 [4],
 [2, 2],
 [3],
 [1],
 [3, 3, 3],
 [4],
 [3],
 [1, 1],
 [2, 2, 2],
 [3]

In [107]:
observations = []
i = 0
for group in grouped_categories:
    
    cat = group[0]
    
    if cat in [5, 6]:
        continue
    
    if i == 0:
        obs = state_models[cat].sample(len(group))[0]
        for o in obs:
            observations.append(o)
    else:
        last_observation = observations[-1]
        
        init_prob = state_models[cat].startprob_
        
#         print(state_models[cat].predict_proba([last_observation]).shape)
        
        state_models[cat].startprob_ = state_models[cat].predict_proba([last_observation])[0]
        
        obs = state_models[cat].sample(len(group))[0]
        
        for o in obs:
            observations.append(o)
        
        state_models[cat].startprob_ = init_prob
        
    i += 1

In [108]:
observations

[array([8.56173357, 0.26708624]),
 array([-0.53411901,  9.25892873]),
 array([-6.34535428,  8.76041523]),
 array([-3.95085717,  7.13766025]),
 array([125.49846723,  16.38377829]),
 array([85.9394739 , 10.25178343]),
 array([87.57108516, 10.68191874]),
 array([94.97164983,  7.31112265]),
 array([124.39539107,  10.53949697]),
 array([45.9137363 , 17.77357234]),
 array([-6.51641948,  0.79104981]),
 array([0.21726239, 1.16463935]),
 array([-23.60677195,   0.78223792]),
 array([41.45559565,  1.58769965]),
 array([39.07058201, 12.40213649]),
 array([52.33819292,  0.80779796]),
 array([63.29597229,  9.89555905]),
 array([99.17077757, 17.84633434]),
 array([89.83150548, 12.74457226]),
 array([128.87999083,   8.95137267]),
 array([80.07735143,  0.25642014]),
 array([155.82649453,   2.60017075]),
 array([-40.89568806,   0.81268986]),
 array([-33.60214839,   7.09492435]),
 array([-43.20116918,   8.1903927 ]),
 array([-39.97997558,   3.99739083]),
 array([70.10374234,  0.70276813]),
 array([129.11

In [76]:
state_models[1].predict_proba([[0.3]])

array([[1.11740913e-021, 3.98609168e-002, 4.30293313e-002,
        5.97618569e-003, 3.69974328e-050, 2.68788566e-003,
        3.91210252e-002, 4.27817350e-029, 8.69324655e-001,
        8.95384038e-147]])